name: impftermin
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project
    steps:
      - uses: actions/checkout@master
      - name: Setup java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build project
        run: mvn -f selenium/pom.xml clean package
      - name: Log into container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Log into docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: build container
        run: |
          docker build -t ghcr.io/tiffel/impftermin:latest .
      - name: push container
        run: docker push ghcr.io/tiffel/impftermin:latest